-- HallOfFame table

ALTER TABLE HALLOFFAME
ADD PRIMARY KEY (PLAYERID, YEARID, VOTEDBY);

INSERT INTO MASTER(PLAYERID)
SELECT PLAYERID FROM HALLOFFAME
WHERE PLAYERID NOT IN  (SELECT PLAYERID FROM MASTER);

ALTER TABLE HALLOFFAME
ADD FOREIGN KEY (PLAYERID) REFERENCES MASTER(PLAYERID);

-- SALARIES table

ALTER TABLE SALARIES
ADD PRIMARY KEY (TEAMID, YEARID, PLAYERID);

SELECT PLAYERID
FROM SALARIES
WHERE PLAYERID NOT IN (SELECT PLAYERID FROM MASTER);

--USING SOLUTION 2
INSERT INTO MASTER(PLAYERID)
SELECT PLAYERID FROM SALARIES
WHERE PLAYERID NOT IN  (SELECT PLAYERID FROM MASTER);

ALTER TABLE SALARIES
ADD FOREIGN KEY (PLAYERID) REFERENCES MASTER(PLAYERID);

--USING SOLUTION 3
SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE SALARIES
ADD FOREIGN KEY (YEARID, LGID, TEAMID) REFERENCES TEAMS(YEARID, LGID, TEAMID );
SET FOREIGN_KEY_CHECKS=1;

-- AWARDSSHAREMANAGERS table

ALTER TABLE AWARDSSHAREMANAGERS
ADD PRIMARY KEY (YEARID, PLAYERID);

--USING SOLUTION 3
SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE AWARDSSHAREMANAGERS
ADD FOREIGN KEY (PLAYERID, AWARDID, YEARID) REFERENCES AWARDSMANAGERS(PLAYERID, AWARDID, YEARID);
SET FOREIGN_KEY_CHECKS=1;

-- AWARDSSHAREPLAYERS table

ALTER TABLE AWARDSSHAREPLAYERS
ADD PRIMARY KEY (AWARDID, YEARID, PLAYERID);

--USING SOLUTION 3
SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE AWARDSSHAREPLAYERS
ADD FOREIGN KEY (PLAYERID, AWARDID, YEARID, LGID) REFERENCES AWARDSPLAYERS(PLAYERID, AWARDID, YEARID, LGID);
SET FOREIGN_KEY_CHECKS=1;

-- COLLEGEPLAYING table

ALTER TABLE COLLEGEPLAYING
ADD PRIMARY KEY (PLAYERID, SCHOOLID, YEARID);

ALTER TABLE COLLEGEPLAYING
ADD FOREIGN KEY (PLAYERID) REFERENCES MASTER(PLAYERID);

--USING SOLUTION 2
SELECT SCHOOLID
FROM COLLEGEPLAYING
WHERE SCHOOLID NOT IN (SELECT SCHOOLID FROM SCHOOLS);

INSERT INTO SCHOOLS(SCHOOLID)
SELECT DISTINCT SCHOOLID FROM COLLEGEPLAYING
WHERE SCHOOLID NOT IN  (SELECT SCHOOLID FROM SCHOOLS);


ALTER TABLE COLLEGEPLAYING
ADD FOREIGN KEY (SCHOOLID) REFERENCES SCHOOLS(SCHOOLID);

