-- master table find primary key
SELECT COUNT(*)
FROM MASTER;

SELECT COUNT(DISTINCT PLAYERID) FROM MASTER;

-- TeamSFranchises table find primary key
SELECT COUNT(*)
FROM TEAMSFRANCHISES;

SELECT COUNT(DISTINCT FRANCHID) FROM TEAMSFRANCHISES;

-- TEAMS table find primary key
SELECT COUNT(*)
FROM TEAMS;

SELECT COUNT(DISTINCT YEARID, LGID, TEAMID) FROM TEAMS;

-- batting table find primary key
SELECT COUNT(*)
From BATTING;

SELECT *
FROM BATTING;

SELECT COUNT(DISTINCT PLAYERID, YEARID, STINT) FROM BATTING;

-- pitching table find primary key
SELECT COUNT(*)
FROM PITCHING;

SELECT COUNT(DISTINCT PLAYERID, YEARID, STINT) FROM PITCHING;

-- fielding table find primary key
SELECT COUNT(*)
FROM FIELDING;

SELECT COUNT(DISTINCT PLAYERID, YEARID, STINT, POS) FROM FIELDING;

-- AllstarFull table find primary key
SELECT COUNT(*)
FROM ALLSTARFULL;

SELECT COUNT(distinct PLAYERID, YEARID, GAMENUM) FROM ALLSTARFULL;

-- HallOfFame table find primary key
SELECT COUNT(*)
FROM HALLOFFAME;

SELECT COUNT(DISTINCT PLAYERID, YEARID, VOTEDBY) FROM HALLOFFAME;

-- Managers table find primary key
SELECT COUNT(*)
FROM MANAGERS;

SELECT COUNT(DISTINCT PLAYERID, YEARID, INSEASON) FROM MANAGERS;

-- BATTINGPOST table find primary key
SELECT COUNT(*)
FROM BATTINGPOST;

SELECT COUNT(DISTINCT YEARID, ROUND, PLAYERID) FROM BATTINGPOST;

-- PITCHINGPOST table find primary key
SELECT COUNT(*)
FROM PITCHINGPOST;

SELECT COUNT(DISTINCT YEARID, ROUND, PLAYERID) FROM PITCHINGPOST;

-- FIELDINGOF table find primary key
SELECT COUNT(*)
FROM FIELDINGOF;

SELECT COUNT(DISTINCT PLAYERID, YEARID, STINT) FROM FIELDINGOF;

-- MANAGERSHALF table find primary key
SELECT COUNT(*)
FROM MANAGERSHALF;

SELECT COUNT(DISTINCT PLAYERID, HALF) FROM MANAGERSHALF;

-- TEAMSHALF table find primary key
SELECT COUNT(*)
FROM TEAMSHALF;

SELECT COUNT(DISTINCT TEAMID, HALF) FROM TEAMSHALF;

-- SALARIES table find primary key
SELECT COUNT(*)
FROM SALARIES;

SELECT COUNT(DISTINCT TEAMID, YEARID ,PLAYERID) FROM SALARIES;

-- SERIESPOST table find primary key
SELECT COUNT(*)
FROM SERIESPOST;

SELECT COUNT(DISTINCT YEARID, ROUND) FROM SERIESPOST;

-- AWARDSMANAGERS table find primary key
SELECT COUNT(*)
FROM AWARDSMANAGERS;

SELECT COUNT(DISTINCT PLAYERID, AWARDID,YEARID) FROM AWARDSMANAGERS;

-- AWARDSPLAYERS table find primary key
SELECT COUNT(*)
FROM AWARDSPLAYERS;

SELECT COUNT(DISTINCT PLAYERID, AWARDID, YEARID, LGID) FROM AWARDSPLAYERS;

-- AWARDSSHAREMANAGERS table find primary key
SELECT COUNT(*)
FROM AWARDSSHAREMANAGERS;

SELECT COUNT(DISTINCT YEARID, PLAYERID) FROM AWARDSSHAREMANAGERS;

-- AWARDSSHAREPLAYERS table find primary key
SELECT COUNT(*)
FROM AWARDSSHAREPLAYERS;

SELECT COUNT(DISTINCT AWARDID, YEARID, PLAYERID) FROM AWARDSSHAREPLAYERS;

-- FIELDINGPOST table find primary key
SELECT COUNT(*)
FROM FIELDINGPOST;

SELECT COUNT(DISTINCT PLAYERID, YEARID, ROUND, POS) FROM FIELDINGPOST;

-- APPEARANCES table find primary key
SELECT COUNT(*)
FROM APPEARANCES;

SELECT COUNT(DISTINCT YEARID, TEAMID, PLAYERID) FROM APPEARANCES;

-- SCHOOLS table find primary key
SELECT COUNT(*)
FROM SCHOOLS;

SELECT COUNT(DISTINCT SCHOOLID) FROM SCHOOLS;

-- COLLEGEPLAYING table find primary key
SELECT COUNT(*)
FROM COLLEGEPLAYING;

SELECT COUNT(DISTINCT PLAYERID, SCHOOLID,YEARID) FROM COLLEGEPLAYING;

-- FIELDINGOFSPLIT table find primary key
SELECT COUNT(*)
FROM FIELDINGOFSPLIT;

SELECT COUNT(DISTINCT PLAYERID,YEARID, STINT,POS) FROM FIELDINGOFSPLIT;

-- PARKS table find primary key
SELECT COUNT(*)
FROM PARKS;

SELECT COUNT(DISTINCT `PARK.KEY`) FROM PARKS;

-- HOMEGAMES table find primary key
SELECT COUNT(*)
FROM HOMEGAMES;

SELECT COUNT(DISTINCT `YEAR.KEY`,`TEAM.KEY`, `PARK.KEY`) FROM HOMEGAMES;
