SELECT COUNT(DISTINCT Game_ID) FROM Initial_chess;
SELECT COUNT(DISTINCT Rated) FROM Initial_chess;
SELECT COUNT(DISTINCT Start_time) FROM Initial_chess;
SELECT COUNT(DISTINCT End_time) FROM Initial_chess;
SELECT COUNT(DISTINCT Number_of_Turns) FROM Initial_chess;
SELECT COUNT(DISTINCT Game_Status) FROM Initial_chess;
SELECT COUNT(DISTINCT Winner) FROM Initial_chess;
SELECT COUNT(DISTINCT Time_Increment) FROM Initial_chess;
SELECT COUNT(DISTINCT White_Player_ID) FROM Initial_chess;
SELECT COUNT(DISTINCT White_Player_Rating) FROM Initial_chess;
SELECT COUNT(DISTINCT Black_Player_ID) FROM Initial_chess;
SELECT COUNT(DISTINCT Black_Player_Rating) FROM Initial_chess;
SELECT COUNT(DISTINCT moves) FROM Initial_chess;
SELECT COUNT(DISTINCT Opening_Eco) FROM Initial_chess;
SELECT COUNT(DISTINCT Opening_Name) FROM Initial_chess;
SELECT COUNT(DISTINCT Opening_Ply) FROM Initial_chess;
SELECT COUNT(DISTINCT Game_ID, Start_time) FROM Initial_chess;
