-- master table

ALTER TABLE MASTER
ADD PRIMARY KEY (PLAYERID);


-- TeamSFranchises table

ALTER TABLE TEAMSFRANCHISES
ADD PRIMARY KEY (FRANCHID);

-- TEAMS table

ALTER TABLE TEAMS
ADD PRIMARY KEY (YEARID, LGID, TEAMID);
ALTER TABLE TEAMS
ADD FOREIGN KEY (FRANCHID) REFERENCES TEAMSFRANCHISES(FRANCHID);


-- batting table

ALTER TABLE BATTING
ADD PRIMARY KEY (PLAYERID, YEARID, STINT);

ALTER TABLE BATTING
ADD FOREIGN KEY (PLAYERID) REFERENCES MASTER(PLAYERID);

ALTER TABLE BATTING
ADD FOREIGN KEY (YEARID, LGID, TEAMID) REFERENCES TEAMS(YEARID, LGID, TEAMID);

-- pitching table

ALTER TABLE PITCHING
ADD PRIMARY KEY (PLAYERID, YEARID, STINT);

ALTER TABLE PITCHING
ADD FOREIGN KEY (PLAYERID) REFERENCES MASTER(PLAYERID);

ALTER TABLE PITCHING
ADD FOREIGN KEY (YEARID, LGID, TEAMID) REFERENCES TEAMS(YEARID, LGID, TEAMID);

-- fielding table

ALTER TABLE FIELDING
ADD PRIMARY KEY (PLAYERID, YEARID, STINT, POS);

ALTER TABLE FIELDING
ADD FOREIGN KEY (PLAYERID) REFERENCES MASTER(PLAYERID);

ALTER TABLE FIELDING
ADD FOREIGN KEY (YEARID, LGID, TEAMID) REFERENCES TEAMS(YEARID, LGID, TEAMID);


-- AllstarFull table

ALTER TABLE ALLSTARFULL
ADD PRIMARY KEY (PLAYERID, YEARID, GAMENUM);

ALTER TABLE ALLSTARFULL
ADD FOREIGN KEY (PLAYERID) REFERENCES MASTER(PLAYERID);

ALTER TABLE ALLSTARFULL
ADD FOREIGN KEY (YEARID, LGID, TEAMID) REFERENCES TEAMS(YEARID, LGID, TEAMID);


-- Managers table

ALTER TABLE MANAGERS
ADD PRIMARY KEY (PLAYERID, YEARID, INSEASON);

ALTER TABLE MANAGERS
ADD FOREIGN KEY (PLAYERID) REFERENCES MASTER(PLAYERID);

ALTER TABLE MANAGERS
ADD FOREIGN KEY (YEARID, LGID, TEAMID) REFERENCES TEAMS(YEARID, LGID, TEAMID);

-- BATTINGPOST table

ALTER TABLE BATTINGPOST
ADD PRIMARY KEY (YEARID, ROUND, PLAYERID);

ALTER TABLE BATTINGPOST
ADD FOREIGN KEY (PLAYERID) REFERENCES MASTER(PLAYERID);

ALTER TABLE BATTINGPOST
ADD FOREIGN KEY (YEARID, LGID, TEAMID) REFERENCES TEAMS(YEARID, LGID, TEAMID);

-- PITCHINGPOST table

ALTER TABLE PITCHINGPOST
ADD PRIMARY KEY (YEARID, ROUND, PLAYERID);

ALTER TABLE PITCHINGPOST
ADD FOREIGN KEY (PLAYERID) REFERENCES MASTER(PLAYERID);

ALTER TABLE PITCHINGPOST
ADD FOREIGN KEY (YEARID, LGID, TEAMID) REFERENCES TEAMS(YEARID, LGID, TEAMID);


-- FIELDINGOF table

ALTER TABLE FIELDINGOF
ADD PRIMARY KEY (PLAYERID, YEARID, STINT);

ALTER TABLE FIELDINGOF
ADD FOREIGN KEY (PLAYERID) REFERENCES MASTER(PLAYERID);

-- MANAGERSHALF table

ALTER TABLE MANAGERSHALF
ADD PRIMARY KEY (PLAYERID, HALF);

ALTER TABLE MANAGERSHALF
ADD FOREIGN KEY (PLAYERID, YEARID, INSEASON) REFERENCES MANAGERS(PLAYERID, YEARID, INSEASON);

-- TEAMSHALF table

ALTER TABLE TEAMSHALF
ADD PRIMARY KEY (TEAMID, HALF);

ALTER TABLE TEAMSHALF
ADD FOREIGN KEY (YEARID, LGID, TEAMID ) REFERENCES TEAMS(YEARID, LGID, TEAMID );


-- SERIESPOST table

ALTER TABLE SERIESPOST
ADD PRIMARY KEY (YEARID, ROUND);

ALTER TABLE SERIESPOST
ADD FOREIGN KEY (YEARID, lgIDwinner, teamIDwinner) REFERENCES TEAMS(YEARID,LGID,TEAMID);

ALTER TABLE SERIESPOST
ADD FOREIGN KEY (YEARID, lgIDloser, teamIDloser) REFERENCES TEAMS(YEARID,LGID,TEAMID);

-- AWARDSMANAGERS table

ALTER TABLE AWARDSMANAGERS
ADD PRIMARY KEY (PLAYERID, AWARDID, YEARID);

ALTER TABLE AWARDSMANAGERS
ADD FOREIGN KEY (PLAYERID) REFERENCES MASTER(PLAYERID);

-- AWARDSPLAYERS table

ALTER TABLE AWARDSPLAYERS
ADD PRIMARY KEY (PLAYERID, AWARDID, YEARID, LGID);

ALTER TABLE AWARDSPLAYERS
ADD FOREIGN KEY (PLAYERID) REFERENCES MASTER(PLAYERID);


-- FIELDINGPOST table

ALTER TABLE FIELDINGPOST
ADD PRIMARY KEY (PLAYERID, YEARID, ROUND, POS);

ALTER TABLE FIELDINGPOST
ADD FOREIGN KEY (PLAYERID) REFERENCES MASTER(PLAYERID);

ALTER TABLE FIELDINGPOST
ADD FOREIGN KEY (YEARID, LGID, TEAMID) REFERENCES TEAMS(YEARID, LGID, TEAMID);

-- APPEARANCES table

ALTER TABLE APPEARANCES
ADD PRIMARY KEY (YEARID, TEAMID, PLAYERID);

ALTER TABLE APPEARANCES
ADD FOREIGN KEY (PLAYERID) REFERENCES MASTER(PLAYERID);

ALTER TABLE APPEARANCES
ADD FOREIGN KEY (YEARID, LGID, TEAMID) REFERENCES TEAMS(YEARID, LGID, TEAMID);


-- SCHOOLS table

ALTER TABLE SCHOOLS
ADD PRIMARY KEY (SCHOOLID);


-- FIELDINGOFSPLIT table

ALTER TABLE FIELDINGOFSPLIT
ADD PRIMARY KEY (PLAYERID, YEARID, STINT, POS);


ALTER TABLE FIELDINGOFSPLIT
ADD FOREIGN KEY (YEARID, LGID, TEAMID) REFERENCES TEAMS(YEARID, LGID, TEAMID);

-- PARKS table

ALTER TABLE PARKS
ADD PRIMARY KEY (`PARK.KEY`);

-- HOMEGAMES table

ALTER TABLE HOMEGAMES
ADD PRIMARY KEY (`YEAR.KEY`, `TEAM.KEY`, `PARK.KEY`);

ALTER TABLE HOMEGAMES
ADD FOREIGN KEY (`PARK.KEY`) REFERENCES PARKS(`PARK.KEY`);

ALTER TABLE HOMEGAMES
ADD FOREIGN KEY (`YEAR.KEY`, `LEAGUE.KEY`, `TEAM.KEY` ) REFERENCES TEAMS(YEARID, LGID, TEAMID);

-- HallOfFame table

ALTER TABLE HALLOFFAME
ADD PRIMARY KEY (PLAYERID, YEARID, VOTEDBY);

INSERT INTO MASTER(PLAYERID)
SELECT PLAYERID FROM HALLOFFAME
WHERE PLAYERID NOT IN  (SELECT PLAYERID FROM MASTER);

ALTER TABLE HALLOFFAME
ADD FOREIGN KEY (PLAYERID) REFERENCES MASTER(PLAYERID);

-- SALARIES table

ALTER TABLE SALARIES
ADD PRIMARY KEY (TEAMID, YEARID, PLAYERID);

SELECT PLAYERID
FROM SALARIES
WHERE PLAYERID NOT IN (SELECT PLAYERID FROM MASTER);

-- USING SOLUTION 2
INSERT INTO MASTER(PLAYERID)
SELECT PLAYERID FROM SALARIES
WHERE PLAYERID NOT IN  (SELECT PLAYERID FROM MASTER);


ALTER TABLE SALARIES
ADD FOREIGN KEY (PLAYERID) REFERENCES MASTER(PLAYERID);

-- USING SOLUTION 3
SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE SALARIES
ADD FOREIGN KEY (YEARID, LGID, TEAMID) REFERENCES TEAMS(YEARID, LGID, TEAMID );
SET FOREIGN_KEY_CHECKS=1;

-- AWARDSSHAREMANAGERS table

ALTER TABLE AWARDSSHAREMANAGERS
ADD PRIMARY KEY (YEARID, PLAYERID);

-- USING SOLUTION 3
SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE AWARDSSHAREMANAGERS
ADD FOREIGN KEY (PLAYERID, AWARDID, YEARID) REFERENCES AWARDSMANAGERS(PLAYERID, AWARDID, YEARID);
SET FOREIGN_KEY_CHECKS=1;

-- AWARDSSHAREPLAYERS table

ALTER TABLE AWARDSSHAREPLAYERS
ADD PRIMARY KEY (AWARDID, YEARID, PLAYERID);

-- USING SOLUTION 3
SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE AWARDSSHAREPLAYERS
ADD FOREIGN KEY (PLAYERID, AWARDID, YEARID, LGID) REFERENCES AWARDSPLAYERS(PLAYERID, AWARDID, YEARID, LGID);
SET FOREIGN_KEY_CHECKS=1;

-- COLLEGEPLAYING table

ALTER TABLE COLLEGEPLAYING
ADD PRIMARY KEY (PLAYERID, SCHOOLID, YEARID);

ALTER TABLE COLLEGEPLAYING
ADD FOREIGN KEY (PLAYERID) REFERENCES MASTER(PLAYERID);

-- USING SOLUTION 2
SELECT SCHOOLID
FROM COLLEGEPLAYING
WHERE SCHOOLID NOT IN (SELECT SCHOOLID FROM SCHOOLS);

INSERT INTO SCHOOLS(SCHOOLID)
SELECT DISTINCT SCHOOLID FROM COLLEGEPLAYING
WHERE SCHOOLID NOT IN  (SELECT SCHOOLID FROM SCHOOLS);


ALTER TABLE COLLEGEPLAYING
ADD FOREIGN KEY (SCHOOLID) REFERENCES SCHOOLS(SCHOOLID);

